### PR TITLE
chore(spa): add environment provider

### PR DESCRIPTION
**Pull request by timonmasberg**
This is required for accessing the environment from our libs. Otherwise, we would have a crazy import to our app from a lib (../../../../....../environment...) which nx complains about. With the Provider, we can easily access our environment through the `APP_CONFIG` injection token in the libraries.

### CODE REVIEW

**Comment by JSPRH** [comment]
Great idea to inject the environment via `InjectionToken` to make it easily accessible. However, I really dislike that we have to touch files in two different “packages” to change the environment (SPA app and app-config lib). I think this runs contrary to loose coupling between packages. How about moving the environment interface into `app/spa/src/environments/environment.ts` as well?

**Comment by timonmasberg** [comment]
> ake it easily accessible. However, I really dislike that we have to touch files in two different “packages” to change the environment (SPA app and app-config lib). I think this runs contrary to loose coupling between packages. How about moving the environment in

The idea behind that is, that we only have 1 Import. When we use the Token, we likely also need the Type. But I understand that it is not good to have 2 packages we need to adjust. We could also move the environment folder into the lib, which i dislike because we would break the default angular setup. Or we could follow [this approach.](https://github.com/nrwl/nx/issues/208#issuecomment-503165673) which is entirely different. Please share your thoughts on this.

**Comment by JSPRH** [comment]
I think we should avoid having a dedicated package for anything environment-related at all. As the environment is tightly coupled to the app, it should live within the app's space. 

How about [doing it like we used to](https://gitlab.com/kordis-ag/app/-/blob/develop/tsconfig.json#L20-21) with our legacy system by having a `paths` entry in the app-specific `tsconfig`?

**Comment by timonmasberg** [comment]
> I think we should avoid having a dedicated package for anything environment-related at all. As the environment is tightly coupled to the app, it should live within the app's space.
> 
> How about [doing it like we used to](https://gitlab.com/kordis-ag/app/-/blob/develop/tsconfig.json#L20-21) with our legacy system by having a `paths` entry in the app-specific `tsconfig`?

Yes, this is the approach the link mentions. Do you think `@kordis/spa/env` would be a good name for that?

**Comment by JSPRH** [comment]
Compared to the approach the link mentions, I would rather have the environment staying in the `spa` folder instead of having an `environment` folder in the repo's root. That's why I suggested the solution we are using in our legacy system. As written above, I think we should keep handling the environment as a matter of each app and not enforce one way of doing environment on all apps. That said, I would stay with `@env/` for the environment path.

**Comment by timonmasberg** [comment]
> Compared to the approach the link mentions, I would rather have the environment staying in the `spa` folder instead of having an `environment` folder in the repo's root. That's why I suggested the solution we are using in our legacy system. As written above, I think we should keep handling the environment as a matter of each app and not enforce one way of doing environment on all apps. That said, I would stay with `@env/` for the environment path.

yes, i was just referring to the path alias. We have to declare the path in the root tsconfig since we want to use it in the app and in the libs. The only change would be to add `apps/spa/src/environments/environment.ts` to the tsconfig.base. Therefore, we must use spa in the name, so we can use the same procedure for our backend app and libs.

would `@env/spa` be good?

**Comment by JSPRH** [comment]
Why do you want to use the env in the libs anyway? This would create a cyclic dependency (SPA importing lib importing SPA for its env). Besides, injection of information should work more like with `RouterModule` IMHO anyway. And if no packages besides SPA needs its environment, we can restrict the `path` to its `tsconfig`.

**Comment by timonmasberg** [comment]
> Besides, injection of information should work more like with `RouterModule` IMHO any way to ensure loose coupling. And if no packages besides SPA needs its environment, we can restrict the `path` to its `tsconfig`.

App acts as a shell, it only contains its first level routes, components, and dependencies and nothing more. [A feature module lives under libs,](https://nx.dev/more-concepts/library-types#feature-libraries) the feature module definitely needs access to environment variables (such as production flag, api url etc). Libs are nothing more than modules or groups of standalone units. Ofc if we define shared libs they should not use the environment of an app. I agree that this is hard since we do not want the “circular dependency” (which could easily be resolved with `import type`) and we would rather not open the environment to the complete monorepo. I suggest that we talk about that in our weekly.

**Comment by timonmasberg** [comment]
Weekly update:

We will check if it is even necessary to have a “global”-environment throughout the app and its libraries. First, we will write all feature modules fully configurable without relying on the environment. Until then, this is stale.

**Comment by timonmasberg** [comment]
Closing this for now because in https://github.com/kordis-leitstelle/kordis/pull/76 it is not needed, and I think it won't be necessary, as we should configure everything from the app.

**Pull request closed without merging**
