### PR TITLE
ci: introduce semantic release

### PR DESCRIPTION
**Pull request by timonmasberg**
# Description

Introducing semantic-versioning as a first step towards our migration to the gitops repo. Now, we release a version fully automatic with semantic-versioning and build and publish images on release. Following, we have to move the sentry release, as well as the complete deployment to the infra repo.

# Checklist:

- [x] The title of this PR and the commit history is conform with
	the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) specification.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings, SonarCloud reports no Vulnerabilities, Bugs or Code Smells.
- [x] I have added tests (unit and E2E if user-facing) that prove my fix is effective or that my feature works,
	Coverage > 80% and not less than the current coverage of the main branch.
- [x] The PR branch is up-to-date with the base branch. In case you merged `main` into your feature branch, make sure you have run the latest NX migrations (`nx migrate --run-migrations`).

### CODE REVIEW

**Comment by JSPRH** [comment]
I think this is not required anymore, right?

https://github.com/kordis-leitstelle/kordis/blob/a9b09e3111e289893f45d5965235bc2e55653352/.github/actions/build-and-publish-spa/action.yml#L55-L61

**Comment by JSPRH** [comment]
Why do you use the flow 
`On push to main --> release --> build and publish containers`
and not
`On push to main --> build and publish containers --> release`?

**Comment by JSPRH** [comment]
Are the tests run in `.github/actions/build-and-publish-api/action.yml` respective `.github/actions/build-and-publish-spa/action.yml`? I couldn't find them 🤔

**Comment by timonmasberg** [comment]
> Are the tests run in `.github/actions/build-and-publish-api/action.yml` respective `.github/actions/build-and-publish-spa/action.yml`? I couldn't find them 🤔

no, the action is just a composite that can be used in any workflow (see `.github/workflows/publish.yml`). We run tests in the `ci.yml`, do you also want them to run before we release? Since pull requests always need to be up-to-date when merging, the state that gets build and publish is always tested (best-case)

**Comment by timonmasberg** [comment]
> Why do you use the flow `On push to main --> release --> build and publish containers` and not `On push to main --> build and publish containers --> release`?

3 reasons:
1. we should be able to create a release manually, which should trigger the build of the images
2. semantic versioning might not always create a release (e.g. for ci, docs ...)
3. we only know what version the release is, after semantic-release ran, and therefore it must come after the release

An alternative would be to put the building and publishing of the images in the release workflow, but it seems like it is not quite easy to determine the version number from the semantic-release procedure: https://github.com/semantic-release/semantic-release/issues/753.

**Review by JSPRH — DISMISSED** [review]
Great work! Looking forward to seeing this in action 👀

**Review by JSPRH — DISMISSED** [review]

**Pull request merged**
