### PR TITLE
chore: add AGPLv3 license

### LINKED ISSUE #3: Choose a license
As we aim to be “open-source” we should choose a license pretty quickly to have no liability or warranty issues. Furthermore, we need to discuss if we want to be truly open source or license Kordis under a non-commercial license which would prevent someone to sell Kordis or create a SaaS layer over it. An example license would be the Elastic License, which technically is not an open-source license!

My choice would be a [General Public License](https://choosealicense.com/licenses/agpl-3.0/) that specifies that source code of distributed material from Kordis must be available under the same license, which, I think, is more than fair.

### PR DESCRIPTION
**Pull request by JSPRH**
Adds GNU AGPLv3 license as discussed in #3.

Closes #3.

### CODE REVIEW

**Comment by timonmasberg** [comment]
Could you add `LICENSE.md` to the `.prettierignore`

**Comment by JSPRH** [comment]
Seems like the `LICENSE.md` breaks something with the code coverage. Can you please have a look at it @timonmasberg?

**Comment by timonmasberg** [comment]
> Seems like the `LICENSE.md` breaks something with the code coverage. Can you please have a look at it @timonmasberg?

Somehow the coverage report breaks when there are no changes, I'll check it out soonish.

**Comment by timonmasberg** [comment]
please pull main, possible fix addressed in https://github.com/kordis-leitstelle/kordis/commit/1c05e6a8d2360a3e79b305737306011531388b65

**Review by timonmasberg — APPROVED** [review]
lgtm

**Pull request merged**
