### PR TITLE
chore: introduce ant design & remove tailwind

### PR DESCRIPTION
**Pull request by timonmasberg**
# Description

This introduced [ant design](https://ant.design/) via the [ng-zorro](https://ng.ant.design/docs/introduce/en) package and removes Tailwind as a dependency. We should be fine with vanilla css and a components library. Furthermore, it migrates to the new [`application`](https://angular.io/guide/esbuild) builder, which uses esbuild under the hood.

# Checklist:

- [x] The title of this PR and the commit history is conform with
	the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) specification.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings, SonarCloud reports no Vulnerabilities, Bugs or Code Smells.
- [x] I have added tests (unit and E2E if user-facing) that prove my fix is effective or that my feature works,
	Coverage > 80% and not less than the current coverage of the main branch.
- [x] The PR branch is up-to-date with the base branch. In case you merged `main` into your feature branch, make sure you have run the latest NX migrations (`nx migrate --run-migrations`).

### CODE REVIEW

**Review by JSPRH — APPROVED** [review]

**Comment by lppedd** [comment]
@timonmasberg instead of working with with the `NzIconModule`, **only** import the `NzIconDirective` in components where you are using `<span nz-icon ...>`.

Get rid of all imports from `@ant-design/icons-angular`, and statically link ant-design icons through `assets`:
```json
{
  "assets": [
    {
      "glob": "**/*",
      "input": "./node_modules/@ant-design/icons-angular/src/inline-svg/",
      "output": "/assets/"
    }
  ]
}
```

**Comment by timonmasberg** [comment]
> @timonmasberg instead of working with with the `NzIconModule`, **only** import the `NzIconDirective` in components where you are using `<span nz-icon ...>`.
> 
> 
> 
> Get rid of all imports from `@ant-design/icons-angular`, and statically link ant-design icons through `assets`:
> 
> ```json
> 
> {
> 
>   "assets": [
> 
>     {
> 
>       "glob": "**/*",
> 
>       "input": "./node_modules/@ant-design/icons-angular/src/inline-svg/",
> 
>       "output": "/assets/"
> 
>     }
> 
>   ]
> 
> }
> 
> ```
> 
> 
> 
> Edit: note that you can filter down what you include in the assets, e.g.:
> 
> ```
> 
> "glob": "outline/(code|setting).svg"
> 
> ```
> 
> If you don't do that, you end up with megabytes worth of SVGs.
> 
> 

Thanks, we will definitely check it out. What I thought is, that when using `NzIconModule` and register only the icons needed, it will kinda treeshake for those icons.

**Comment by lppedd** [comment]
Yeah, I'd have expected the same.

It looks like ANT for React has more maintenance activity compared to Angular. So I expect more issues being present.

I've did a lot of work with NG-ZORRO back in 2020 and it was at peak activity. Seems development has slowed down.

**Comment by lppedd** [comment]
I don't think you'll find other Angular UI toolkits with the same features NG-ZORRO has.

What I did back then was contributing as soon as I hit blockers, a couple of times maybe. So I encourage to do the same.

If you want maximum community support the only way is switching to React.

**Comment by lppedd** [comment]
What I want to understand is why original Alibaba devs are still bring assigned PR reviews and issues if they don't contribute anymore. And never reply as far as I can see.

**Comment by JSPRH** [comment]
Good question. Thanks for your thoughts. As we are decided on Angular, switching to React is not an option. However, we will keep an eye on dev activity.

**Comment by timonmasberg** [comment]
No need to stress about dev activity. Commits might not be the best indicator of how a project develops, but it seems there is a relatively steady contribution to the project: https://github.com/NG-ZORRO/ng-zorro-antd/graphs/contributors

Furthermore, lately a lot of refactoring towards Standalone Components and the new Angular Control Flow has been done, therefore I wouldnt say the project is slowly dying. What can be seen is that the devs do not focus on Community issues, which is not unusual for projects that are used by big corps as they focus on internal issues first.

**Comment by lppedd** [comment]
Not wrong. But PRs seem to be opened and closed by the same 3/4 people.  
I wouldn't mind it being a slow paced projects, but if a PR takes weeks to be merged, it looks like a problem to me.  
I think the involved people need to clarify who's doing what.

I have a couple of projects that are using NG-ZORRO, so I'm committed on it. Previous point on PRs is what scares me.

**Pull request merged**
